from PIL import Image, ImageOps, ImageDraw, ImageFont
import os


def make_concept_grid(
    image_paths,
    output_path="merged.png",
    concept_names=None,
    images_per_concept=8,
    concept_cols=2,
    concept_rows=4,
    num_concepts=3,
    cell_size=(512, 512),
    padding=10,
    concept_gap=30,
    add_concept_title=False,
    title_height=50,
    bg_color=(255, 255, 255),

    method_name="Mix ODE/SDE",   # 新增：方法名
    caption_prompts=None,        # 新增：caption 里显示的 prompt
    add_caption=True,            # 新增：是否加底部 caption
    caption_height=90,           # 新增：底部 caption 区域高度
    max_caption_font_size=42,
    min_caption_font_size=20,
):
    """
    image_paths: 长度必须为 num_concepts * images_per_concept
    默认:
        3 个 concept
        每个 concept 8 张图
        每个 concept 2列4行
        总图 6列4行
    """

    expected = num_concepts * images_per_concept
    if len(image_paths) != expected:
        raise ValueError(f"需要 {expected} 张图，但你给了 {len(image_paths)} 张。")

    if concept_names is None:
        concept_names = [f"Concept {i+1}" for i in range(num_concepts)]

    if len(concept_names) != num_concepts:
        raise ValueError("concept_names 的长度必须等于 num_concepts。")

    if caption_prompts is None:
        caption_prompts = concept_names

    if len(caption_prompts) != num_concepts:
        raise ValueError("caption_prompts 的长度必须等于 num_concepts。")

    cell_w, cell_h = cell_size

    # 每个 concept 的宽高
    one_concept_width = concept_cols * cell_w + (concept_cols - 1) * padding
    one_concept_height = concept_rows * cell_h + (concept_rows - 1) * padding

    extra_title_h = title_height if add_concept_title else 0
    extra_caption_h = caption_height if add_caption else 0

    canvas_width = (
        num_concepts * one_concept_width
        + (num_concepts - 1) * concept_gap
    )
    canvas_height = one_concept_height + extra_title_h + extra_caption_h

    canvas = Image.new("RGB", (canvas_width, canvas_height), bg_color)
    draw = ImageDraw.Draw(canvas)

    def get_font(size):
        candidate_fonts = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/Library/Fonts/Arial.ttf",
            "arial.ttf",
        ]
        for fp in candidate_fonts:
            try:
                return ImageFont.truetype(fp, size=size)
            except Exception:
                continue
        return ImageFont.load_default()

    def fit_single_line_font(text, max_width, max_size, min_size):
        for size in range(max_size, min_size - 1, -2):
            font = get_font(size)
            bbox = draw.textbbox((0, 0), text, font=font)
            w = bbox[2] - bbox[0]
            h = bbox[3] - bbox[1]
            if w <= max_width:
                return font, w, h
        font = get_font(min_size)
        bbox = draw.textbbox((0, 0), text, font=font)
        w = bbox[2] - bbox[0]
        h = bbox[3] - bbox[1]
        return font, w, h

    for concept_idx in range(num_concepts):
        start = concept_idx * images_per_concept
        end = start + images_per_concept
        concept_paths = image_paths[start:end]

        x_offset = concept_idx * (one_concept_width + concept_gap)
        y_offset = extra_title_h

        if add_concept_title:
            title = concept_names[concept_idx]
            draw.text((x_offset + 10, 10), title, fill=(0, 0, 0))

        for i, img_path in enumerate(concept_paths):
            if not os.path.exists(img_path):
                raise FileNotFoundError(f"找不到图片: {img_path}")

            img = Image.open(img_path).convert("RGB")
            img = ImageOps.fit(img, (cell_w, cell_h), method=Image.Resampling.LANCZOS)

            row = i // concept_cols
            col = i % concept_cols

            paste_x = x_offset + col * (cell_w + padding)
            paste_y = y_offset + row * (cell_h + padding)

            canvas.paste(img, (paste_x, paste_y))

    # 底部总 caption
    if add_caption:
        quoted_prompts = [f'"{p}"' for p in caption_prompts]
        if len(quoted_prompts) == 1:
            prompt_str = quoted_prompts[0]
        elif len(quoted_prompts) == 2:
            prompt_str = f"{quoted_prompts[0]} and {quoted_prompts[1]}"
        else:
            prompt_str = ", ".join(quoted_prompts[:-1]) + f", and {quoted_prompts[-1]}"

        caption_text = f'Images generated by {method_name} for the prompts {prompt_str}.'

        max_text_width = canvas_width - 40
        font, text_w, text_h = fit_single_line_font(
            caption_text,
            max_width=max_text_width,
            max_size=max_caption_font_size,
            min_size=min_caption_font_size
        )

        text_x = (canvas_width - text_w) // 2
        text_y = one_concept_height + extra_title_h + (caption_height - text_h) // 2

        draw.text((text_x, text_y), caption_text, fill=(0, 0, 0), font=font)

    canvas.save(output_path)
    print(f"Saved to {output_path}")


if __name__ == "__main__":
    image_paths = [
        # concept 1: 8 张
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/00.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/01.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/02.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/03.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/04.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/05.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/06.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bicycle/imgs/a_photo_of_a_bicycle_seed1111_g3.0_s30/07.png",

        # concept 2: 8 张
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/00.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/01.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/02.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/03.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/00.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/05.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/06.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_bus/imgs/a_photo_of_a_bus_seed1111_g3.0_s30/07.png",

        # concept 3: 8 张
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/00.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/01.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/02.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/03.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/04.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/10.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/06.png",
        "/data2/toby/OSCAR/outputs/apg_baseline_truck/imgs/a_photo_of_a_truck_seed1111_g3.0_s30/07.png",
    ]

    concept_names = ["truck", "bus", "bicycle"]

    make_concept_grid(
        image_paths=image_paths,
        output_path="apg.png",
        concept_names=concept_names,
        cell_size=(512, 512),
        padding=8,
        concept_gap=24,
        add_concept_title=False,

        method_name="APG",
        caption_prompts=[
            "a photo of a bicycle",
            "a photo of a bus",
            "a photo of a truck",
        ],
        add_caption=True,
        caption_height=100,
        max_caption_font_size=44,
        min_caption_font_size=22,
    )